config/routes.rb
Rails.application.routes.draw do
  resources :guides
  root 'guides#index'

end

app/models/guide.rb
class Guide < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  before_action :set_guide, only: [:show, :edit, :update, :destroy]

  # GET /guides
  # GET /guides.json
  def index
    @guides = Guide.all
  end

  # GET /guides/1
  # GET /guides/1.json
  def show
    @guide = Guide.find(params[:id])
  end

  # GET /guides/new
  def new
    @guide = Guide.new
  end

  # GET /guides/1/edit
  def edit
  end

  # POST /guides
  # POST /guides.json
  def create
    @guide = Guide.new(guide_params)

    respond_to do |format|
      if @guide.save
        format.html { redirect_to @guide, notice: 'Guide was successfully created.' }
        format.json { render :show, status: :created, location: @guide }
      else
        format.html { render :new }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guides/1
  # PATCH/PUT /guides/1.json
  def update
    respond_to do |format|
      if @guide.update(guide_params)
        format.html { redirect_to @guide, notice: 'Guide was successfully updated.' }
        format.json { render :show, status: :ok, location: @guide }
      else
        format.html { render :edit }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guides/1
  # DELETE /guides/1.json
  def destroy
    @guide.destroy
    respond_to do |format|
      format.html { redirect_to guides_url, notice: 'Guide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guide
      @guide = Guide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guide_params
      params.require(:guide).permit(:nickname, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/views/guides/_form.html.erb
<%= form_for(@guide) do |f| %>
  <% if @guide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guide.errors.count, "error") %> prohibited this guide from being saved:</h2>

      <ul>
      <% @guide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guides/edit.html.erb
<h1>Editing Guide</h1>

<%= render 'form' %>

<%= link_to 'Show', @guide %> |
<%= link_to 'Back', guides_path %>

app/views/guides/index.html.erb
  <!-- Menu -->
  <nav class="menu" id="theMenu">
    <div class="menu-wrap">
      <h1 class="logo"><a href="index.html#home">Chat Guide</a></h1>
      <i class="icon-remove menu-close"></i>
      <a href="#home" class="smoothScroll">Home</a>
      <a href="#services" class="smoothScroll">Services</a>
      <a href="#portfolio" class="smoothScroll">Portfolio</a>
      <a href="#about" class="smoothScroll">About</a>
      <a href="#contact" class="smoothScroll">Contact</a>
<!--       <a href="#"><i class="icon-facebook"></i></a>
      <a href="#"><i class="icon-twitter"></i></a>
      <a href="#"><i class="icon-dribbble"></i></a>
      <a href="#"><i class="icon-envelope"></i></a> -->
    </div>
    <!-- Menu button -->
    <div id="menuToggle">
    <!-- <i class="icon-reorder"></i> -->
     <a href="#">log in</a>
    </div>
  </nav>
  <!-- ========== HEADER SECTION ========== -->
  <section id="home" name="home"></section>
  <div id="headerwrap">
    <div class="container">
      <br>
      <h1>Chat Guides</h1>
      <h2>Ask local English Speakers</h2>
      <div class="row">
        <br>
        <br>
        <br>
        <div class="col-lg-6 col-lg-offset-3">
        </div>
      </div>
    </div><!-- /container -->
  </div><!-- /headerwrap -->

  <!-- ========== WHITE SECTION ========== -->
  <div id="w">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
        <h3>Ask  <bold>Local English speakers's ideas</bold> for your trip<br/>
        </h3>
        </div>
      </div>
    </div><!-- /container -->
  </div><!-- /w -->

  <!-- ========== SERVICES - GREY SECTION ========== -->
<!--   <section id="services" name="services"></section>
  <div id="g">
    <div class="container">
      <div class="row">
        <h3>OUR GUIDES</h3>
        <br>
        <br>
        <div class="col-lg-3">
          <img src="assets/s1.png">
          <h4>London</h4>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever.</p>
        </div>
        <div class="col-lg-3">
          <img src="assets/s2.png">
          <h4>Berlin</h4>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever.</p>
        </div>
        <div class="col-lg-3">
          <img src="assets/s3.png">
          <h4>Paris</h4>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever.</p>
        </div>
        <div class="col-lg-3">
          <img src="assets/s4.png">
          <h4>Tokyo</h4>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever.</p>
        </div>
      </div> -->
    <!-- </div>/container -->
  <!-- </div>/ -->

  <!-- ========== CHARTS - DARK GREY SECTION ========== -->
<!--   <div id="dg">
    <div class="container">
      <div class="row">
        <h3>SOME CHARTS</h3>
        <br>
        <br>
        <div class="col-lg-4">
          <canvas id="javascript" height="130" width="130"></canvas>
          <br>
          <h4>Javascript</h4>
          <br>
          <script>
            var doughnutData = [
                {
                  value: 70,
                  color:"#f85c37"
                },
                {
                  value : 30,
                  color : "#ecf0f1"
                }
              ];
              var myDoughnut = new Chart(document.getElementById("javascript").getContext("2d")).Doughnut(doughnutData);
          </script>

        </div>
        <div class="col-lg-4">
          <canvas id="bootstrap" height="130" width="130"></canvas>
          <br>
          <h4>Bootstrap</h4>
          <br>
          <script>
            var doughnutData = [
                {
                  value: 90,
                  color:"#f85c37"
                },
                {
                  value : 10,
                  color : "#ecf0f1"
                }
              ];
              var myDoughnut = new Chart(document.getElementById("bootstrap").getContext("2d")).Doughnut(doughnutData);
          </script>
        </div>
        <div class="col-lg-4">
          <canvas id="wordpress" height="130" width="130"></canvas>
          <br>
          <h4>Wordpress</h4>
          <br>
          <script>
            var doughnutData = [
                {
                  value: 55,
                  color:"#f85c37"
                },
                {
                  value : 45,
                  color : "#ecf0f1"
                }
              ];
              var myDoughnut = new Chart(document.getElementById("wordpress").getContext("2d")).Doughnut(doughnutData);
          </script>
        </div>
      </div>
    </div>/container
  </div>/dg

  <section id="portfolio" name="portfolio"></section>
  <div id="portfoliowrap">
    <div class="container">
      <div class="row">
        <h3>COOL WORKS</h3>
        <br>
        <br>
        <div class="col-lg-4 port-space">
          <a href="item.html"><img src="assets/work1.png"></a>
        </div>
        <div class="col-lg-4 port-space">
          <a href="item.html"><img src="assets/work2.png"></a>
        </div>
        <div class="col-lg-4 port-space">
          <a href="item.html"><img src="assets/work3.png"></a>
        </div>
      </div> -->
    <!-- </div>/container -->
  <!-- </div>/portfoliowrap

  <! ========== WHITE SECTION ==========
  <div id="w">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
        <h3>WE WORK HARD TO DELIVER A <bold>HIGH QUALITY SERVICE</bold>. OUR AIM IS YOUR COMPLETE <bold>SATISFACTION</bold>.
        </h3>
        </div>
      </div>
    </div><! /container -->
  <!-- </div>/-->

  <!-- ========== ABOUT - GREY SECTION ========== -->
  <section id="about" name="about"></section>
  <div id="g">
    <div class="container">
      <div class="row">
        <h3>GUIDES</h3>
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
        </div>
        <div class="col-lg-2"></div>

        <% @guides.each do |guide| %>
          <a href="guides/<%= guide.id %>">
          <div class="col-lg-3 team">
            <img class="img-circle" src="<%= guide.image%>" height="90" width="90">
            <h4><%= guide.nickname %></h4>
            <h5><i><%= guide.title %></i></h5>
            <p>
              <a href="#" class="btn btn-chat">Ley's Chat</a>
<!--               <a href="index.html#"><i class="icon-facebook"></i></a>
              <a href="index.html#"><i class="icon-twitter"></i></a>
              <a href="index.html#"><i class="icon-envelope"></i></a> -->
            </p>
          </div>
          </a>
        <% end %>
<!-- 
        <div class="col-lg-3 team">
          <img class="img-circle" src="assets/team02.jpg" height="90" width="90">
          <h4>Brad Casey</h4>
          <h5><i>Front-end Developer</i></h5>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
          <p>
            <a href="index.html#"><i class="icon-facebook"></i></a>
            <a href="index.html#"><i class="icon-twitter"></i></a>
            <a href="index.html#"><i class="icon-envelope"></i></a>

          </p>
        </div>

        <div class="col-lg-3 team">
          <img class="img-circle" src="assets/team03.jpg" height="90" width="90">
          <h4>Pamela Chow</h4>
          <h5><i>Web Designer</i></h5>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
          <p>
            <a href="index.html#"><i class="icon-facebook"></i></a>
            <a href="index.html#"><i class="icon-twitter"></i></a>
            <a href="index.html#"><i class="icon-envelope"></i></a>

          </p>
        </div>

        <div class="col-lg-3 team">
          <img class="img-circle" src="assets/team04.jpg" height="90" width="90">
          <h4>Tim Gates</h4>
          <h5><i>Back-end Guru</i></h5>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
          <p>
            <a href="index.html#"><i class="icon-facebook"></i></a>
            <a href="index.html#"><i class="icon-twitter"></i></a>
            <a href="index.html#"><i class="icon-envelope"></i></a>

          </p>
        </div> -->
      </div>
    </div><!-- /container -->
  </div><!-- /g -->



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

app/views/guides/new.html.erb
<h1>New Guide</h1>

<%= render 'form' %>

<%= link_to 'Back', guides_path %>

app/views/guides/show.html.erb
  <!-- Menu -->
  <nav class="menu" id="theMenu">
    <div class="menu-wrap">
      <h1 class="logo"><a href="index.html#home">Chat Guide</a></h1>
      <i class="icon-remove menu-close"></i>
      <a href="#home" class="smoothScroll">Home</a>
      <a href="#services" class="smoothScroll">Services</a>
      <a href="#portfolio" class="smoothScroll">Portfolio</a>
      <a href="#about" class="smoothScroll">About</a>
      <a href="#contact" class="smoothScroll">Contact</a>
<!--       <a href="#"><i class="icon-facebook"></i></a>
      <a href="#"><i class="icon-twitter"></i></a>
      <a href="#"><i class="icon-dribbble"></i></a>
      <a href="#"><i class="icon-envelope"></i></a> -->
    </div>
    <!-- Menu button -->
    <div id="menuToggle">
    <!-- <i class="icon-reorder"></i> -->
     <a href="#">log in</a>
    </div>
  </nav>
  <!-- ========== HEADER SECTION ========== -->


  <!-- ========== WHITE SECTION ========== -->


  <!-- ========== SERVICES - GREY SECTION ========== -->

  <!-- ========== WHITE SECTION ==========
  <div id="w">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
        <h3>WE WORK HARD TO DELIVER A <bold>HIGH QUALITY SERVICE</bold>. OUR AIM IS YOUR COMPLETE <bold>SATISFACTION</bold>.
        </h3>
        </div>
      </div>
    </div><! /container -->
  <!-- </div>/-->

  <!-- ========== ABOUT - GREY SECTION ========== -->
  <section id="about" name="about"></section>
  <div id="g">
    <div class="container">
      <div class="row">
        <h3>GUIDES</h3>
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
        </div>
        <div class="col-lg-2"></div>

        <div class="col-lg-3 team">
          <img class="img-circle" src="<%= @guide.image%>" height="90" width="90">
          <h4><%= @guide.nickname %></h4>
          <h5><i><%= @guide.title %></i></h5>
          <p><%= @guide.text %></p>
          <p>
            <a href="#" class="btn btn-chat">Ley's Chat</a>
<!--               <a href="index.html#"><i class="icon-facebook"></i></a>
            <a href="index.html#"><i class="icon-twitter"></i></a>
            <a href="index.html#"><i class="icon-envelope"></i></a> -->
          </p>
        </div>
<!--
        <div class="col-lg-3 team">
          <img class="img-circle" src="assets/team02.jpg" height="90" width="90">
          <h4>Brad Casey</h4>
          <h5><i>Front-end Developer</i></h5>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
          <p>
            <a href="index.html#"><i class="icon-facebook"></i></a>
            <a href="index.html#"><i class="icon-twitter"></i></a>
            <a href="index.html#"><i class="icon-envelope"></i></a>

          </p>
        </div>

        <div class="col-lg-3 team">
          <img class="img-circle" src="assets/team03.jpg" height="90" width="90">
          <h4>Pamela Chow</h4>
          <h5><i>Web Designer</i></h5>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
          <p>
            <a href="index.html#"><i class="icon-facebook"></i></a>
            <a href="index.html#"><i class="icon-twitter"></i></a>
            <a href="index.html#"><i class="icon-envelope"></i></a>

          </p>
        </div>

        <div class="col-lg-3 team">
          <img class="img-circle" src="assets/team04.jpg" height="90" width="90">
          <h4>Tim Gates</h4>
          <h5><i>Back-end Guru</i></h5>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
          <p>
            <a href="index.html#"><i class="icon-facebook"></i></a>
            <a href="index.html#"><i class="icon-twitter"></i></a>
            <a href="index.html#"><i class="icon-envelope"></i></a>

          </p>
        </div> -->
      </div>
    </div><!-- /container -->
  </div><!-- /g -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/ico/favicon.png">

    <title>Chat Guide</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
<!-- Bootstrap core CSS -->
<!--     <link href="/assets/css/bootstrap.css" rel="stylesheet">

    <! Custom styles for this template -->
    <!-- <link href="assets/css/main.css" rel="stylesheet"> -->
    <!-- <link rel="stylesheet" href="assets/css/font-awesome.min.css"> -->

    <!-- <script src="assets/js/jquery.min.js"></script> -->
    <!-- <script src="assets/js/Chart.js"></script> -->
    <!-- <script src="assets/js/modernizr.custom.js"></script> -->

    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="assets/js/html5shiv.js"></script>
      <script src="assets/js/respond.min.js"></script>
    <![endif]-->
  </head>
  <body data-spy="scroll" data-offset="0" data-target="#theMenu">
  <%= yield %>
    <!-- ========== FOOTER SECTION ========== -->
  <section id="contact" name="contact"></section>
  <div id="f">
    <div class="container">
      <div class="row">
          <h3><b>CONTACT US</b></h3>
          <div class="col-lg-4">
            <h3>Message : George@jpneasy.com</h3>
          </div>
          <div class="col-lg-4">
            <h3>Call : +55 3984-4389</h3>
          </div>

          <div class="col-lg-4">
            <h3>We Are Social</h3>
            <p>
              <a href="index.html#"><i class="icon-facebook"></i></a>
              <a href="index.html#"><i class="icon-twitter"></i></a>
              <a href="index.html#"><i class="icon-envelope"></i></a>
            </p>
          </div>
        </div>
      </div>
    </div><!-- /container -->
  </div><!-- /f -->

  <div id="c">
    <div class="container">
      <p>Created by <a href="http://www.blacktie.co">BLACKTIE.CO</a></p>

    </div>
  </div>
  </body>
</html>